import { MetadataRoute } from 'next'

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = 'https://www.ignek.com'

  const staticRoutes = [
    '',
    '/about-us',
    '/career',
    '/blog',
    '/contact',
    '/marketplace',
    '/case-study',
    '/webinars',
  ].map((route) => ({
    url: `${baseUrl}${route}`,
  }))

  const serviceRoutes = [
    '/services/liferay-architecture-design',
    '/services/liferay-consulting-and-implementation-services',
    '/services/liferay-development-and-customization',
    '/services/liferay-ecommerce-development',
    '/services/liferay-expert-advice',
    '/services/liferay-hire-developer',
    '/services/liferay-migration',
    '/services/liferay-performance-tuning',
    '/services/liferay-proof-of-concept',
    '/services/liferay-support-and-maintenance',
    '/services/liferay-theme-development',
    '/services/liferay-upgrade',
  ].map((route) => ({
    url: `${baseUrl}${route}`,
  }))

  const portfolioRoutes: MetadataRoute.Sitemap = [
    { url: `${baseUrl}/portfolio/employee-intranet-portal-for-government-entity` },
    { url: `${baseUrl}/portfolio/public-enterprise-website-for-laundry-services` },
    { url: `${baseUrl}/portfolio/liferay-dxp-based-intranet-portal-migration` },
    { url: `${baseUrl}/portfolio/restaurant-promotion-platform-maximizing-offer-uptake-and-revenue` },
    { url: `${baseUrl}/portfolio/music-license-management-portal` },
    { url: `${baseUrl}/portfolio/epf-government-enterprise-website` },
    { url: `${baseUrl}/portfolio/healthcare-training-mentorship-portal` },
    { url: `${baseUrl}/portfolio/government-job-platform` },
    { url: `${baseUrl}/portfolio/ecommerce-platform-for-sales-rentals` },
    { url: `${baseUrl}/portfolio/incident-management-portal` },
    { url: `${baseUrl}/portfolio/blogging-application` },
    { url: `${baseUrl}/portfolio/social-portal-for-company-users` },
    { url: `${baseUrl}/portfolio/informative-portal-for-n-g-o` },
    { url: `${baseUrl}/portfolio/enterprise-customer-portal` },
    { url: `${baseUrl}/portfolio/reimbursement-portal-for-ngo` },
    { url: `${baseUrl}/portfolio/medical-consultant-portal` },
    { url: `${baseUrl}/portfolio/government-finance-public-website` },
    { url: `${baseUrl}/portfolio/helicopter-reservation-portal` },
    { url: `${baseUrl}/portfolio/waste-management-portal` },
    { url: `${baseUrl}/portfolio/dam-solution-using-liferay` },
    { url: `${baseUrl}/portfolio/partner-portal` },
    { url: `${baseUrl}/portfolio/invoice-based-leading-finance-portal` },
    { url: `${baseUrl}/portfolio/statistics-center-portal` },
    { url: `${baseUrl}/portfolio/multimedia-portal` },
    { url: `${baseUrl}/portfolio/telecommunications-portal` },
    { url: `${baseUrl}/portfolio/migration-to-liferay-dxp-portal` },
    { url: `${baseUrl}/portfolio/unified-digital-platform` },
    { url: `${baseUrl}/portfolio/agenda-and-meeting-saas-platform` },
    { url: `${baseUrl}/portfolio/patient-portal-with-fhir-interoperability` },
  ]

  const blogRoutes: MetadataRoute.Sitemap = [
    { url: `${baseUrl}/blog/blog-react-polling-websockets-comparison` },
    { url: `${baseUrl}/blog/blog-liferay-oauth2-microservice-scopes` },
    { url: `${baseUrl}/blog/blog-liferay-css-extension-vs-theme-css` },
    { url: `${baseUrl}/blog/blog-liferay-google-analytics-gtm-setup` },
    { url: `${baseUrl}/blog/blog-firebase-otp-login-phone-auth-react` },
    { url: `${baseUrl}/blog/blog-firebase-login-facebook-google-integration-react` },
    { url: `${baseUrl}/blog/blog-firebase-react-login-google-auth` },
    { url: `${baseUrl}/blog/blog-react-zustand-dashboard-guide` },
    { url: `${baseUrl}/blog/blog-save-for-later-local-storage` },
    { url: `${baseUrl}/blog/blog-liferay-search-filter-vs-facet` },
    { url: `${baseUrl}/blog/blog-liferay-headless-api-security-oauth2` },
    { url: `${baseUrl}/blog/blog-liferay-collections-segments-personalization` },
    { url: `${baseUrl}/blog/blog-liferay-site-template-overview` },
    { url: `${baseUrl}/blog/blog-liferay-sprite-map-customization` },
    { url: `${baseUrl}/blog/blog-liferay-login-events-overview` },
    { url: `${baseUrl}/blog/blog-liferay-client-extensions-overview` },
    { url: `${baseUrl}/blog/comparison-of-client-extensions-and-osgi-modern-vs-traditional-liferay-development` },
    { url: `${baseUrl}/blog/blog-liferay-blueprints-search-suggestions` },
    { url: `${baseUrl}/blog/blog-dotnet-liferay-integration` },
    { url: `${baseUrl}/blog/blog-graphql-liferay-guide` },
    { url: `${baseUrl}/blog/blog-liferay-frontend-boost-lighthouse-scores` },
    { url: `${baseUrl}/blog/blog-configure-saml-liferay-dxp` },
    { url: `${baseUrl}/blog/creating-and-using-information-templates-for-liferay-blogs` },
    { url: `${baseUrl}/blog/blog-secure-token-storage-react-best-practices` },
    { url: `${baseUrl}/blog/blog-liferay-object-api-headless-custom-crud` },
    { url: `${baseUrl}/blog/blog-react-state-management-context-redux-recoil-zustand` },
    { url: `${baseUrl}/blog/blog-customize-liferay-login-fragment` },
    { url: `${baseUrl}/blog/blog-trigger-object-actions-client-extensions-microservices` },
    { url: `${baseUrl}/blog/blog-react-breadcrumb-component` },
    { url: `${baseUrl}/blog/blog-google-maps-react-integration` },
    { url: `${baseUrl}/blog/blog-microservice-client-extension-liferay` },
    { url: `${baseUrl}/blog/blog-liferay-data-sets-customer-feedback` },
    { url: `${baseUrl}/blog/blog-webrtc-react-video-call` },
    { url: `${baseUrl}/blog/blog-infinite-scroll-react-hook` },
    { url: `${baseUrl}/blog/blog-publish-npm-package` },
    { url: `${baseUrl}/blog/blog-liferay-publications-guide` },
    { url: `${baseUrl}/blog/blog-liferay-object-collections` },
    { url: `${baseUrl}/blog/blog-react-patterns-clean-code` },
    { url: `${baseUrl}/blog/blog-liferay-page-template` },
    { url: `${baseUrl}/blog/blog-undo-redo-react-form` },
    { url: `${baseUrl}/blog/blog-build-chrome-extension-react` },
    { url: `${baseUrl}/blog/blog-liferay-virtual-instance-setup-guide` },
    { url: `${baseUrl}/blog/blog-liferay-forms-widget-survey-guide` },
    { url: `${baseUrl}/blog/blog-csr-vs-ssr-rendering-guide` },
    { url: `${baseUrl}/blog/blog-semantic-versioning-guide-caret-tilde-asterisk` },
    { url: `${baseUrl}/blog/blog-react-window-virtualization-large-list` },
    { url: `${baseUrl}/blog/blog-lockfiles-dependency-security-npm-yarn-pnpm` },
    { url: `${baseUrl}/blog/liferay-categories-tags-organize-content` },
    { url: `${baseUrl}/blog/ratings-feature-using-liferay-ootb` },
    { url: `${baseUrl}/blog/delivering-personalized-experiences-in-liferay-using-segments-and-behavioral-data` },
    { url: `${baseUrl}/blog/powering-liferay-object-views-category-based-filtering` },
    { url: `${baseUrl}/blog/setting-up-liferay-with-postgresql-using-docker` },
    { url: `${baseUrl}/blog/theme-vs-no-theme-how-to-configure-stylebooks-in-liferay` },
    { url: `${baseUrl}/blog/using-rest-client-in-freemarker-instead-of-service-locator` },
    { url: `${baseUrl}/blog/sharing-websocket-connections-between-browser-tabs-and-windows` },
    { url: `${baseUrl}/blog/seamlessly-integrating-slack-with-node-js` },
    { url: `${baseUrl}/blog/no-more-asset-publisher-render-web-content-with-collection-providers` },
    { url: `${baseUrl}/blog/integrating-google-tasks-with-node-js-a-comprehensive-guide` },
    { url: `${baseUrl}/blog/generating-text-content-images-using-ai-in-liferay` },
    { url: `${baseUrl}/blog/implementing-backend-pagination-with-material-ui-in-react` },
    { url: `${baseUrl}/blog/integrating-google-calendar-with-node-js-a-comprehensive-guide` },
    { url: `${baseUrl}/blog/qr-code-generator-app` },
    { url: `${baseUrl}/blog/creating-and-using-information-templates-in-liferay` },
    { url: `${baseUrl}/blog/implement-infinite-scrolling-in-react-by-using-intersection-observers-api` },
    { url: `${baseUrl}/blog/how-to-handle-scope-creep-without-disrupting-your-project` },
    { url: `${baseUrl}/blog/how-to-speed-up-your-wordpress-site-with-image-optimization` },
    { url: `${baseUrl}/blog/stream-api-in-java` },
    { url: `${baseUrl}/blog/mastering-the-solid-principles-in-software-development` },
    { url: `${baseUrl}/blog/securing-your-wordpress-site-key-steps-every-developer-should-take` },
    { url: `${baseUrl}/blog/centralized-logging-system-for-liferay` },
    { url: `${baseUrl}/blog/implementing-a-centralized-logging-system-for-liferay` },
    { url: `${baseUrl}/blog/data-visualization-in-react-integrating-victory-chart-for-stunning-visuals` },
    { url: `${baseUrl}/blog/multi-step-form-with-liferay-objects` },
    { url: `${baseUrl}/blog/scheduling-tasks-in-spring-boot-applications` },
    { url: `${baseUrl}/blog/matomo-integration-with-liferay` },
    { url: `${baseUrl}/blog/api-headers-demystified-a-guide-for-react-js-developers` },
    { url: `${baseUrl}/blog/optimizing-graphql-queries-in-react-applications` },
    { url: `${baseUrl}/blog/integrate-whatsapp-with-twilio-in-spring-boot` },
    { url: `${baseUrl}/blog/building-a-micro-front-end-architecture-with-react-and-module-federation` },
    { url: `${baseUrl}/blog/building-a-micro-frontend-architecture-with-react-and-next-js` },
    { url: `${baseUrl}/blog/top-wordpress-page-builders-compared-elementor-vs-divi-vs-gutenberg` },
    { url: `${baseUrl}/blog/api-builder-in-liferay` },
    { url: `${baseUrl}/blog/how-to-use-actuator-effectively-with-spring-boot` },
    { url: `${baseUrl}/blog/how-to-build-a-multilingual-website-with-wordpress` },
    { url: `${baseUrl}/blog/implementing-authentication-in-react-oauth-vs-jwt-vs-session-based-authentication` },
    { url: `${baseUrl}/blog/managing-the-state-and-validation-in-liferay-objects` },
    { url: `${baseUrl}/blog/enhance-liferay-portal-performance-using-adaptive-media` },
    { url: `${baseUrl}/blog/best-practices-for-working-with-spring-boot` },
    { url: `${baseUrl}/blog/apache-kafka-with-custom-objects-in-spring-boot` },
    { url: `${baseUrl}/blog/payment-gateway-integration-with-spring-boot` },
    { url: `${baseUrl}/blog/the-best-newsletter-plugins-for-wordpress-in-2024` },
    { url: `${baseUrl}/blog/types-of-enterprise-web-portals` },
    { url: `${baseUrl}/blog/performance-measurement-in-liferay` },
    { url: `${baseUrl}/blog/google-login-integration-in-liferay` },
    { url: `${baseUrl}/blog/liferay-7-4-features-against-7-2-features` },
    { url: `${baseUrl}/blog/crud-application-with-react-and-spring-boot` },
    { url: `${baseUrl}/blog/solving-healthcare-challenges-through-liferay-dxp` },
    { url: `${baseUrl}/blog/essential-intellij-shortcuts-every-java-developer-should-know` },
    { url: `${baseUrl}/blog/possible-ways-to-customize-the-liferay` },
    { url: `${baseUrl}/blog/exploring-key-java-features-from-versions-9-to-21` },
    { url: `${baseUrl}/blog/liferay-cms-for-content-management` },
    { url: `${baseUrl}/blog/integrating-thymeleaf-into-spring-boot` },
    { url: `${baseUrl}/blog/google-analytics-with-liferay-client-extension` },
    { url: `${baseUrl}/blog/implementing-react-routing` },
    { url: `${baseUrl}/blog/java-8-top-20-features-comprehensive-guide` },
    { url: `${baseUrl}/blog/microservice-architecture-in-liferay` },
    { url: `${baseUrl}/blog/liferay-portal-migration-guide` },
    { url: `${baseUrl}/blog/react-insights-choosing-between-uselayouteffect-and-useeffect` },
    { url: `${baseUrl}/blog/protect-your-business-data-with-intranet-solutions` },
    { url: `${baseUrl}/blog/build-and-deploy-nestjs-apps-with-docker` },
    { url: `${baseUrl}/blog/end-to-end-testing-nodejs-app-quality` },
    { url: `${baseUrl}/blog/react-batching-for-performance-optimization` },
    { url: `${baseUrl}/blog/build-scalable-saas-applications-with-liferay` },
    { url: `${baseUrl}/blog/boost-spring-boot-performance-with-redis-caching` },
    { url: `${baseUrl}/blog/model-document-contributor-in-liferay` },
    { url: `${baseUrl}/blog/optimizing-large-lists-in-react-virtualization-vs-pagination` },
    { url: `${baseUrl}/blog/persisting-react-state-in-localstorage` },
    { url: `${baseUrl}/blog/building-secure-payment-gateways-with-node-js` },
    { url: `${baseUrl}/blog/securing-your-node-js-apps-with-helmet` },
    { url: `${baseUrl}/blog/centralized-exception-handling-in-spring-boot` },
    { url: `${baseUrl}/blog/dependency-injection-in-nestjs` },
    { url: `${baseUrl}/blog/calendar-events-detail-page-in-liferay` },
    { url: `${baseUrl}/blog/why-choose-nestjs-over-plain-node-js-for-enterprise-level-applications` },
    { url: `${baseUrl}/blog/transforming-data-into-insights-with-liferay-and-ai` },
    { url: `${baseUrl}/blog/transform-customer-experiences-with-liferay-dxp` },
    { url: `${baseUrl}/blog/liferay-dxp-healthcare-patient-driven-solutions` },
    { url: `${baseUrl}/blog/service-access-policy-in-liferay` },
    { url: `${baseUrl}/blog/safeguard-your-react-js-web-app` },
    { url: `${baseUrl}/blog/use-of-liferay-blueprint-with-collection` },
    { url: `${baseUrl}/blog/ootb-chat-integration-with-liferay` },
    { url: `${baseUrl}/blog/build-scalable-enterprise-websites-with-liferay` },
    { url: `${baseUrl}/blog/custom-element-using-client-extension` },
    { url: `${baseUrl}/blog/building-multi-step-forms-in-react` },
    { url: `${baseUrl}/blog/dockerized-microservices-in-springboot` },
    { url: `${baseUrl}/blog/liferay-ecommerce-personalized-shopping-experiences` },
    { url: `${baseUrl}/blog/handling-large-data-with-infinite-scrolling-in-react` },
    { url: `${baseUrl}/blog/distributed-tracing-microservices-springboot` },
    { url: `${baseUrl}/blog/twilio-sms-integration-with-liferay` },
    { url: `${baseUrl}/blog/how-dxps-revolutionize-financial-services` },
    { url: `${baseUrl}/blog/liferay-customer-portal-best-practices` },
    { url: `${baseUrl}/blog/liferay-is-the-ideal-intranet-portal-solution` },
    { url: `${baseUrl}/blog/creating-forms-in-react-with-react-hook-form` },
    { url: `${baseUrl}/blog/creating-react-form-with-formik` },
    { url: `${baseUrl}/blog/liferay-dxp-for-healthcare-platform` },
    { url: `${baseUrl}/blog/liferay-blueprint-and-how-we-can-use-it` },
    { url: `${baseUrl}/blog/modern-intranet-boost-employee-engagement-and-collaboration` },
    { url: `${baseUrl}/blog/simplifying-global-state-react-usecontext-usereducer` },
    { url: `${baseUrl}/blog/building-resilient-spring-boot-microservices-circuit-breaker-resilience4j` },
    { url: `${baseUrl}/blog/dxps-vs-traditional-cms-modern-enterprises-need-more-than-cms` },
    { url: `${baseUrl}/blog/why-composable-architecture-is-revolutionizing-dxp` },
    { url: `${baseUrl}/blog/transform-your-digital-assets-with-liferays-dam-solution` },
    { url: `${baseUrl}/blog/10-essential-intranet-features-to-boost-success-and-engagement` },
    { url: `${baseUrl}/blog/spring-security-jwt-authentication-authorization` },
    { url: `${baseUrl}/blog/oauth-2-0-authentication-in-spring-boot` },
    { url: `${baseUrl}/blog/liferay-dxp-go-to-for-digital-experience-platform` },
    { url: `${baseUrl}/blog/abdm-unveiled-exploring-milestone-for-next-gen-healthcare-transformations` },
    { url: `${baseUrl}/blog/blog-building-a-scalable-saas-platform-key-strategies-for-success` },
    { url: `${baseUrl}/blog/liferay-form-fragments-and-objects` },
    { url: `${baseUrl}/blog/integrate-ldap-with-liferay` },
    { url: `${baseUrl}/blog/transforming-patient-care-with-dxp-a-healthcare-revolution` },
    { url: `${baseUrl}/blog/future-of-customer-engagement-why-your-business-needs-a-digital-experience-platform-dxp` },
    { url: `${baseUrl}/blog/hipaa-compliant-app-development-for-healthcare` },
    { url: `${baseUrl}/blog/personalized-dxps-are-key-to-customer-loyalty` },
    { url: `${baseUrl}/blog/maximizing-roi-with-liferay-open-source-platform` },
    { url: `${baseUrl}/blog/what-is-abdm-and-its-benefits` },
    { url: `${baseUrl}/blog/what-is-client-extension-how-we-can-use` },
    { url: `${baseUrl}/blog/liferay-site-initializer-using-client-extension` },
    { url: `${baseUrl}/blog/simplifying-state-with-context-api` },
    { url: `${baseUrl}/blog/jira-integration-with-liferay` },
    { url: `${baseUrl}/blog/importance-of-data-interoperability-in-healthcare` },
    { url: `${baseUrl}/blog/zoom-integration-with-liferay` },
    { url: `${baseUrl}/blog/redis-for-liferay-session-management` },
    { url: `${baseUrl}/blog/liferay-low-code-no-code-solution` },
    { url: `${baseUrl}/blog/notification-with-liferay-object` },
    { url: `${baseUrl}/blog/create-a-custom-gogo-shell-command-in-liferay` },
    { url: `${baseUrl}/blog/efficient-log-management-in-liferay` },
    { url: `${baseUrl}/blog/migrating-from-monolith-to-microservices` },
    { url: `${baseUrl}/blog/spring-boot-with-swagger-integration` },
    { url: `${baseUrl}/blog/crud-restful-apis-with-spring-boot` },
    { url: `${baseUrl}/blog/overview-of-object-model-builder` },
    { url: `${baseUrl}/blog/integrate-sonar-with-liferay-workspace` },
    { url: `${baseUrl}/blog/managing-relationships-in-liferay-objects` },
    { url: `${baseUrl}/blog/rendering-data-using-object-and-collection-provider` },
    { url: `${baseUrl}/blog/utilizing-the-no-code-concept-for-liferay-website-branding` },
    { url: `${baseUrl}/blog/website-branding-using-themes-in-liferay` },
    { url: `${baseUrl}/blog/intranet-portal-built-using-liferay` },
    { url: `${baseUrl}/blog/top-10-reasons-to-use-liferay-for-digital-transformation` },
    { url: `${baseUrl}/blog/performance-tuning-with-liferay` },
    { url: `${baseUrl}/blog/dockerize-springboot-application` },
    { url: `${baseUrl}/blog/reactjs-performance-tuning` },
    { url: `${baseUrl}/blog/docker-compose-nodejs-mysql-integration` },
    { url: `${baseUrl}/blog/authentication-and-authorization-in-react` },
    { url: `${baseUrl}/blog/project-management-the-fundamentals` },
    { url: `${baseUrl}/blog/test-graphql-queries-and-mutation-using-rtl-and-jest` },
    { url: `${baseUrl}/blog/maximising-application-efficiency-through-strategic-module-interdependencies-in-react-typescript-with-liferay` },
    { url: `${baseUrl}/blog/liferay-as-a-headless-cms` },
    { url: `${baseUrl}/blog/manufacturing-portal-in-liferay` },
    { url: `${baseUrl}/blog/patient-portal-in-liferay` },
    { url: `${baseUrl}/blog/liferay-dxp-7-4-upgrade` },
    { url: `${baseUrl}/blog/various-approaches-of-api-integration-in-spring-boot` },
    { url: `${baseUrl}/blog/liferay-with-docker` },
    { url: `${baseUrl}/blog/test-react-typescript-component-with-jest-and-rtl` },
    { url: `${baseUrl}/blog/liferay-objects-with-message-bus-2` },
    { url: `${baseUrl}/blog/bulk-data-upload-for-liferay-objects-using-csv` },
    { url: `${baseUrl}/blog/debugging-react-js-and-graphql-in-liferay` },
    { url: `${baseUrl}/blog/common-components-react-typescript-with-liferay` },
    { url: `${baseUrl}/blog/typescript-and-react-with-liferay` },
    { url: `${baseUrl}/blog/custom-annotations-in-spring-boot` },
    { url: `${baseUrl}/blog/apache-kafka-case-studies-pros-and-cons` },
    { url: `${baseUrl}/blog/scheduler-in-liferay-7-4` },
    { url: `${baseUrl}/blog/graphql-with-spring-boot` },
    { url: `${baseUrl}/blog/mail-configuration-in-liferay-with-gmails-increased-security` },
    { url: `${baseUrl}/blog/react-remote-app-with-liferay` },
    { url: `${baseUrl}/blog/react-with-liferay` },
    { url: `${baseUrl}/blog/microsoft-teams-integration-with-liferay` },
    { url: `${baseUrl}/blog/google-meet-integration-with-liferay` },
    { url: `${baseUrl}/blog/start-two-or-more-liferay-servers-simultaneously-on-a-machine` },
    { url: `${baseUrl}/blog/rest-builder-in-liferay-7-x` },
    { url: `${baseUrl}/blog/fragments-in-liferay` },
    { url: `${baseUrl}/blog/create-override-the-language-key-using-liferay-ootb` },
    { url: `${baseUrl}/blog/liferay-object-with-liferay-forms` },
    { url: `${baseUrl}/blog/attach-categories-and-fill-data-in-custom-fields-of-webcontent-with-the-liferay-headless-api` },
    { url: `${baseUrl}/blog/manage-web-content-postman-liferays-headless-api` },
    { url: `${baseUrl}/blog/create-localization-content-liferays-headless-api` },
    { url: `${baseUrl}/blog/liferay-server-autostart-script-in-ubuntu` },
    { url: `${baseUrl}/blog/liferay-user-setting-navigation-override` },
    { url: `${baseUrl}/blog/objects-in-liferay-7-4` },
    { url: `${baseUrl}/blog/liferay-integration-with-google-drive` },
    { url: `${baseUrl}/blog/servlet-filter-in-liferay-7-2` },
    { url: `${baseUrl}/blog/portlet-filter-in-liferay-7-2` },
    { url: `${baseUrl}/blog/context-contributor-in-liferay-7-2` },
    { url: `${baseUrl}/blog/portlet-preferences-in-liferay-7-2` },
    { url: `${baseUrl}/blog/configuration-creator-in-liferay-7-2` },
    { url: `${baseUrl}/blog/change-look-and-feel-of-control-panel` },
    { url: `${baseUrl}/blog/add-custom-portlet-into-control-panel-in-liferay-7-2` },
    { url: `${baseUrl}/blog/how-to-override-liferay-7-portal-javascript` },
    { url: `${baseUrl}/blog/gogo-shell-in-liferay-7-2` },
    { url: `${baseUrl}/blog/create-custom-configurations-in-liferay-7-2` },
    { url: `${baseUrl}/blog/add-custom-language-support-to-liferay-7` },
    { url: `${baseUrl}/blog/scheduler-in-liferay-7-dxp` },
    { url: `${baseUrl}/blog/frequently-used-code-snippets-for-liferay` },
    { url: `${baseUrl}/blog/how-to-write-adt-with-structure-and-template-in-liferay` },
    { url: `${baseUrl}/blog/customize-the-look-and-feel-of-login-portlet-in-liferay` },
    { url: `${baseUrl}/blog/use-captcha-or-recaptcha-with-custom-portlet-in-liferay` },
    { url: `${baseUrl}/blog/service-wrapper-in-liferay-7` },
    { url: `${baseUrl}/blog/crud-operations-in-liferay-portlet-with-custom-entity` },
    { url: `${baseUrl}/blog/how-to-create-model-listeners-in-liferay` },
    { url: `${baseUrl}/blog/liferay-react-portlet` },
  ]

  return [...staticRoutes, ...serviceRoutes, ...portfolioRoutes, ...blogRoutes]
}
